name = "teste_julia"
uuid = "ac1a3a4f-42ce-4d7a-a358-2ba8820ff088"
authors = ["salomaodoretto <daniel.doretto13@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
